name: Python CI

on: [push]

env:
  AZURE_WEBAPP_NAME: akrelativityapp
  AZURE_WEBAPP_PACKAGE_PATH: webapp
  AZURE_FUNCTIONAPP_NAME: akrelativityapp-fun
  AZURE_FUNCTIONAPP_PACKAGE_PATH: function

jobs:
  deploy-to-function:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}


  build-and-test-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collect static
        run: |
          pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          echo "yes" | python manage.py collectstatic
      - name: Deploy web App using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          slot-name: dev
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            webapp/ 
            !venv/
      - name: Run tests
        run: |
          pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          python manage.py test
  deploy-to-webapp:
    needs: build-and-test-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Disable static collection and set migration command on App Service
        uses: Azure/appservice-settings@v1
        with:  
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: '[{ "name": "DISABLE_COLLECTSTATIC", "value": "true" }, { "name": "POST_BUILD_COMMAND",  "value": "python manage.py makemigrations && python manage.py migrate" }, { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }, { "name": "DJANGO_ENV", "value": "production"}]'
      - name: Deploy web App using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
